# Generated by Django 5.0.6 on 2024-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
